version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: ^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$
          message: Semantic release conventions must be followed.
      - do: description
        must_include:
          regex: '[A-Z]{4,6}\-[0-9]{4,6}'
          message: Jira ticket number.
