version: 2
mergeable:
  - when: pull_request.*, pull_request_review.*
    validate:
      - do: title
        must_include:
          regex: '^(feat|docs|chore|fix|refactor|test|style|perf)\:\s[A-Z]{3,5}\-[0-9]{3,5}'
          message: Semantic release conventions must be followed.
      - do: description
        must_include:
          regex: '[A-Z]{4,6}\-[0-9]{4,6}'
          message: Jira ticket number.
      - do: commit
        message:
          regex: '(^Merge|^Revert|^[A-Z]{4,6}\-[0-9]{4,6}).*$'
          message: 'Commit must start with JIRA ticket or merge/revert message.'
      - do: label
        or:
          - must_include:
              regex: 'squash'
              message: 'Label for squash and merge'
          - must_include:
              regex: 'merge'
              message: 'Label for merge'
